apiVersion: v1
kind: Pod
metadata:
  name: cpu-pressure 
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "2"]
    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "500m"
