apiVersion: v1
kind: Pod
metadata:
  name: memory-pressure
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "300M"]
    resources:
      requests:
        memory: "128Mi"
      limits:
        memory: "200Mi"
